import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { languages } from '../i18n/settings'
import { LayoutProps } from '@/types'
import { dir } from 'i18next'

export async function generateStaticParams() {
  return languages.map(lng => ({ lng }))
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js Starter Template with Internationalization',
  description: 'Generated by create next app'
}

export default function RootLayout({ children, params: { lng } }: LayoutProps) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
